// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/theme-variants/Atlas.tsx": () => import("../components/mockups/theme-variants/Atlas.tsx"),
  "./components/mockups/theme-variants/Forge.tsx": () => import("../components/mockups/theme-variants/Forge.tsx"),
  "./components/mockups/theme-variants/Obsidian.tsx": () => import("../components/mockups/theme-variants/Obsidian.tsx")
};
